# src = $(wildcard *.cpp)
# obj = $(patsubst %.cpp, %.o, $(src))

# ALL:server

# server:$(obj)
# 	g++ $(obj) -o server

# server.o:server.cpp
# 	gcc -c server.cpp -o server.0
server:
	g++ server.cpp -o server && \
	g++ client.cpp -o client




